Resources:

  # Lambda Execution Role that will be referenced on the LambdaExecutionPolicy to extend the access to S3
  # This Role is used on the Lambda InterfaceDiagramLambdaS3 to process S3 files
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  # This Policy allow the lambda to process the S3 files
  # Used on the Lambda InterfaceDiagramLambdaS3 
  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaS3Access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::interface-diagram-files
              - arn:aws:s3:::interface-diagram-files/*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "arn:aws:logs:*:*:*"
      Roles:
        - Ref: LambdaExecutionRole
  

  # Lambda Execution Role that will be referenced on the LambdaApiExecutionPolicy
  # This Role is used on the Lambda InterfaceDiagramLambda that process a unique json file from a POST API
  LambdaApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  # This posice allows the lambda to log the event on the Cloud Whatch
  LambdaApiExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaApiExecutionPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      Roles:
        - Ref: LambdaApiExecutionRole

  # This lambda will be exposed by an POST API to process a json body and will return a Draw.io URL of the E2E Flow
  InterfaceDiagramLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: InterfaceDiagram
      Handler: src/main/lambda_api_function.lambda_handler
      Role: !GetAtt [LambdaApiExecutionRole, Arn]
      Code:
        S3Bucket: interface-diagram  # Replace the bucket name by your S3 bucket that contains the lambda zip file
        S3Key: function_api.zip
      Runtime: python3.8
      Timeout: 15

  # This lambda proceess the json files from a S3 and return the Draw.io URLs in a Excel file on a S3 bucket
  InterfaceDiagramLambdaS3:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: InterfaceDiagramS3
      Handler: src/main/lambda_s3_function.lambda_handler
      Role: !GetAtt [LambdaExecutionRole, Arn]
      Code:
        S3Bucket: interface-diagram  # Replace the bucket name by your S3 bucket that contains the lambda zip file
        S3Key: function_s3.zip
      Runtime: python3.8
      Timeout: 900 # Maximum timeout in seconds
      MemorySize: 1024 # Memory size in MB; 1024 is 1GB

  # API to be used on the InterfaceDiagramLambda
  InterfaceDiagramAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: InterfaceDiagramAPI
  
  # API Deployment to be used on the InterfaceDiagramLambda
  InterfaceDiagramDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: InterfaceDiagramMethod
    Properties:
      RestApiId: !Ref InterfaceDiagramAPI
  
  # API Method to be used on the InterfaceDiagramLambda
  InterfaceDiagramMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST
      ResourceId: !GetAtt 
        - InterfaceDiagramAPI
        - RootResourceId
      RestApiId: !Ref InterfaceDiagramAPI
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub 
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Arn}/invocations"
          - Arn: !GetAtt InterfaceDiagramLambda.Arn
      AuthorizationType: NONE
  
  # API Permission to be used on the InterfaceDiagramLambda
  InterfaceDiagramPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt InterfaceDiagramLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${InterfaceDiagramAPI}/*/POST/"
  
  # API Stage to be used on the InterfaceDiagramLambda
  InterfaceDiagramStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      Description: Production Stage
      RestApiId: !Ref InterfaceDiagramAPI
      DeploymentId: !Ref InterfaceDiagramDeployment
  
  # Event to be used on the InterfaceDiagramLambdaS3 to run on a specifc time
  WeeklyLambdaTrigger:
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "Trigger my Lambda function every weekday at 10:00 AM Madrid time"
      ScheduleExpression: "cron(0 8 ? * MON-FRI *)"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "InterfaceDiagramLambdaS3"
              - "Arn"
          Id: "TargetFunctionV1"

  # Permission Event to be used on the InterfaceDiagramLambdaS3 to run on a specifc time
  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties: 
      FunctionName: 
        Ref: "InterfaceDiagramLambdaS3"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "WeeklyLambdaTrigger"
          - "Arn"

# Output to get the API URL for the Lambda InterfaceDiagramLambda
Outputs:
  ApiUrl:
    Description: The URL of the API Gateway for this stack
    Value: !Sub "https://${InterfaceDiagramAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"