name: On Push (main) - CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deploy: 'false'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # (Optional) Set the AWS region. Default is us-east-1.

    - name: Run pylint
      run: pylint src/main/
      
    - name: Run unittest
      run: |
        python -m unittest discover src/tests/
          
    - name: Delete current stack
      if: matrix.deploy == 'true'
      run: 
        aws cloudformation delete-stack --stack-name diagram

    - name: Generate zip files
      if: matrix.deploy == 'true'
      run: |
        python ./scripts/generate_zip.py

    - name: Upload files to S3
      if: matrix.deploy == 'true'
      run: |
        aws s3 cp ./scripts/lambda_api_function.zip s3://interface-diagram/lambda_api_function.zip
        aws s3 cp ./scripts/lambda_s3_function.zip s3://interface-diagram/lambda_s3_function.zip
        aws s3 cp ./scripts/lambda_s3_layer.zip s3://interface-diagram/lambda_s3_layer.zip
        aws s3 cp ./scripts/lambda_function.yaml s3://interface-diagram/lambda_function.yaml

    - name: Wait for stack deletion
      if: matrix.deploy == 'true'
      run: sleep 80
  
    - name: Create new stack
      if: matrix.deploy == 'true'
      run: |
        aws cloudformation create-stack --stack-name diagram \
        --template-url https://interface-diagram.s3.amazonaws.com/lambda_function.yaml \
        --capabilities CAPABILITY_IAM
